tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface": "#131313",
                "surface-dim": "#131313",
                "surface-bright": "#3a3939",
                "surface-container-lowest": "#0e0e0e",
                "surface-container-low": "#1c1b1b",
                "surface-container": "#201f1f",
                "surface-container-high": "#2a2a2a",
                "surface-container-highest": "#353534",
                "on-surface": "#e5e2e1",
                "on-surface-variant": "#e3bfb1",
                "inverse-surface": "#e5e2e1",
                "inverse-on-surface": "#313030",
                "outline": "#aa8a7d",
                "outline-variant": "#5a4136",
                "surface-tint": "#ffb596",
                "primary": "#ffb596",
                "on-primary": "#581e00",
                "primary-container": "#ff6600",
                "on-primary-container": "#561d00",
                "inverse-primary": "#a33e00",
                "secondary": "#c7c6c6",
                "on-secondary": "#2f3131",
                "secondary-container": "#484949",
                "on-secondary-container": "#b8b8b8",
                "tertiary": "#c8c6c5",
                "on-tertiary": "#313030",
                "tertiary-container": "#989696",
                "on-tertiary-container": "#2f2f2f",
                "error": "#ffb4ab",
                "on-error": "#690005",
                "error-container": "#93000a",
                "on-error-container": "#ffdad6",
                "primary-fixed": "#ffdbcd",
                "primary-fixed-dim": "#ffb596",
                "on-primary-fixed": "#360f00",
                "on-primary-fixed-variant": "#7c2e00",
                "secondary-fixed": "#e3e2e2",
                "secondary-fixed-dim": "#c7c6c6",
                "on-secondary-fixed": "#1a1c1c",
                "on-secondary-fixed-variant": "#464747",
                "tertiary-fixed": "#e5e2e1",
                "tertiary-fixed-dim": "#c8c6c5",
                "on-tertiary-fixed": "#1c1b1b",
                "on-tertiary-fixed-variant": "#474746",
                "background": "#131313",
                "on-background": "#e5e2e1",
                "surface-variant": "#353534"
            },
            borderRadius: {
                sm: "0.125rem",
                DEFAULT: "0.25rem",
                md: "0.375rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px"
            },
            spacing: {
                base: "4px",
                "margin-desktop": "64px",
                "margin-mobile": "16px",
                gutter: "24px",
                "container-max": "1440px",
                unit: "4px",
                "max-width-chat": "800px"
            },
            fontFamily: {
                "display-xl": ["Hanken Grotesk"],
                "headline-lg": ["Hanken Grotesk"],
                "headline-lg-mobile": ["Hanken Grotesk"],
                "headline-md": ["Hanken Grotesk"],
                "body-md": ["Inter"],
                "body-lg": ["Inter"],
                "code-sm": ["JetBrains Mono"],
                "code-block": ["JetBrains Mono"],
                "label-caps": ["JetBrains Mono"],
                "label-sm": ["JetBrains Mono"]
            },
            fontSize: {
                "display-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "800" }],
                "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
                "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "code-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
                "code-block": ["13px", { lineHeight: "20px", fontWeight: "400" }],
                "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
                "label-sm": ["11px", { lineHeight: "16px", fontWeight: "700" }]
            }
        }
    }
}
